### ISSUE TITLE
WebDav connection problems via Windows 10 after applying the script

### ISSUE THREAD

**Issue by BeckeBauer** [alexanderharm/syno-webdav-keeweb#2]
When I apply the changes via the script, I noticed a strange behavior with mapped drives under Windows 10.  Firstly, the connection to mapped drive is refused ("location not found" message). When I then disconnect the drive **and** delete the credentials for the mapped drives under control panel - credential manager and reboot the computer, I can then map the drive again. After another reboot, connection to the mapped drive is lost again ("location not found" message) but after disconnection, credential deletion and reboot, mapping can initiated again (and so on). When I delete the WebDav entries created by your script, everything goes back to "normal" (mapping works again also after restart of the computer). Any idea what the problem might cause (and maybe how to improve the script)?

**Comment by alexanderharm** [comment]
Not sure. Maybe it has something to do with the auth type. W10 only does digest, KeeWeb only basic. Did you try and eliminate the settings one by one to find the one causing this?

**Comment by BeckeBauer** [comment]
I reinstalled everything and it works as expected. Cannot determine what caused the issue. Thanks for the attempt to help and sorry for not closing earlier..
