### ISSUE TITLE
Does not work on DSM 7

### ISSUE THREAD

**Issue by jortfal** [alexanderharm/syno-webdav-keeweb#3]
Hi,

In DSM 7 `synoservice` has been replaced by `systemctl`.

Therefore it is necessary to modify the line "_synoservice --restart pkgctl-WebDAVServer_" 

https://github.com/alexanderharm/syno-webdav-keeweb/blob/3e1ec5b84892fefc105809ddefb426d8ee826964/synoWebdavKeeweb.sh#L111

by

`sudo systemctl restart pkgctl-WebDAVServer`

Another option is to manually restart WebDAV => https://www.howtogeek.com/322201/how-to-stop-andrestart-applications-on-your-synology-nas/

Regards

**NOTE:** enable the CORS on webdav server in Synology => https://github.com/keeweb/keeweb/issues/703#issuecomment-326404286

**Comment by alexanderharm** [comment]
Closed via 459dc94 

Thanks a lot for reporting and offering a solution!
